Navbar  welcome page created
tinatsina/web_design_portfolio pull request #1
Opened 2022-05-30 17:34 UTC by tinatsina

created the mobile version of the portfolio website with
-navbar and icon at the right
-images inserted as absolutes
-mobile version of the website created

2022-05-30 18:21 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @tinatsina,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good summary description :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 18:21 UTC, topeogunleye commented on index.html
> +    </div>
- [ ] As required, please, I kindly suggest that you add the Projects section of your portfolio and the about me section. Kindly check your [design templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) for guidance.

| Projects  Section | About me Section |
| ------------- | ------------- |
| ![Screenshot from 2022-05-30 18-59-35](https://user-images.githubusercontent.com/52934128/171042704-b5ec98a1-f49e-4202-9003-dcd173f3d182.png)  | ![Screenshot from 2022-05-30 19-00-03](https://user-images.githubusercontent.com/52934128/171042736-f6e7bc03-d6f4-4466-9a3e-29d3f814de85.png) |
| ![Screenshot from 2022-05-30 18-59-51](https://user-images.githubusercontent.com/52934128/171042720-212faff3-7795-4318-ae7c-037d29dd33da.png) | Content Cell  |

- [ ] Please kindly remember to follow project requirements by:

- Using a section tag for your projects and about me containers
- Please use ul and li for categories in "Work" section. Html, Css, and Javascript should be list items.
- Please use ul and li for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.
- You don't need to implement the detail modal window that requires JavaScript.
- Please kindly stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- Please kindly implement the button interaction (enable, hover, etc.).

![Screenshot from 2022-05-30 19-18-40](https://user-images.githubusercontent.com/52934128/171043750-67fb8647-a70c-4d78-afa1-e89023e135e8.png)

2022-05-30 19:00 UTC, Whoistolu requested changes
Hi @tinatsina 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 11:12 UTC, tinatsina commented on index.html
> +    <div class="top-right-image"></div>
Changed it to header tags

2022-05-31 11:13 UTC, tinatsina commented on index.html
> +    <div class="top-right-image"></div>
Changed to `nav` tag according to project requirements. Also updated to the suggested format.

2022-05-31 11:13 UTC, tinatsina commented on index.html
> +    </section>
Looked thoroughly at the Figma template and updated all missing or un-included errors.

2022-05-31 11:14 UTC, tinatsina commented on index.html
> +                </p>
Added the font and typography to match exactly the template.

2022-05-31 11:32 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @tinatsina,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-31 14:46 UTC, merged